### ISSUE TITLE
`wp-admin/options-writing.php` broken

### ISSUE THREAD

**Issue by pfefferle** [snarfed/wordpress-micropub#125]
The latest version of the plugin is breaking the settings page `wp-admin/options-writing.php`

**Comment by dshanske** [comment]
It is? Maybe the template didn't get included. It is a new file in the push. But it worked when I checked it on my stable site.

**Comment by pfefferle** [comment]
you can check the repo and/or the wordpress svn, if it is present...

**Comment by pfefferle** [comment]
It seems to be missing in the tag: https://plugins.svn.wordpress.org/micropub/tags/1.4/

**Comment by dshanske** [comment]
But @snarfed set stable to trunk

**Comment by dshanske** [comment]
Either way, maybe I will set up that script you use on the other plugins as a PR.

**Comment by dshanske** [comment]
It is in trunk

**Comment by pfefferle** [comment]
but that does not help, because the tag is used

**Comment by dshanske** [comment]
I just pushed it into the tag directory, either way.

**Comment by pfefferle** [comment]
But this does not fix the blogs, that already installed version 1.4.

**Comment by snarfed** [comment]
agreed, this warrants a 1.4.1 release.

the root cause is in `push.sh`. it hard codes the source files, and we didn't add the settings files to it. we should change it to use globbing, or something similar.

**Comment by dshanske** [comment]
Suggest we adopt a new push procedure concurrent with that. WIll see if there is a simple one I can include.

**Comment by dshanske** [comment]
What about something like this? https://github.com/GaryJones/wordpress-plugin-svn-deploy

**Comment by snarfed** [comment]
hmm, maybe, sure! alternatively we could just use the output of `git ls-files`.

mind getting the existing hand-rolled 1.4.1 release out first? then we can figure out this new process for the next one?

**Comment by dshanske** [comment]
I basically took the pieces of that script I liked and created a new one quickly in another plugin of mine.

https://github.com/dshanske/simple-location/blob/master/push.sh

May work on this a bit and see if it might be worth including.

**Comment by dshanske** [comment]
I will hand roll a release. Did we ever decide re the scope work and if it is ready to merge? Could be a 1.5

**Comment by dshanske** [comment]
1.4.1 Pushed.
